services:
  - type: web
    name: phishdetect
    runtime: python
    buildCommand: ""
    startCommand: "python web_app.py"
    envVars:
      - key: FLASK_ENV
        value: production
    autoDeploy: true
