services:
  - type: web
    name: phishdetect
    runtime: python
    buildCommand: ""
    startCommand: "gunicorn web_app:app"
    envVars:
      - key: FLASK_ENV
        value: production
    autoDeploy: true
